### ISSUE TITLE
Check-in Agenda 

### ISSUE THREAD

**Issue by mlkhorn** [mlkhorn/ftc_cosore#12]
- [x] discuss recently written code
- [x] discuss filling in gaps in CO2 flux data
- [x] discuss removing years with only a few months of data (`d20190617_SCOTT_WKG` dataset contains two full years of data, and one year with only 5 months of data in the winter and spring, other datasets have similar problems)

**Comment by stephpenn1** [comment]
@bpbond when calculating annual Rs... is there a minimum amount of Rs data we need?

Do we need representation from each season? each month?

#### For example? One dataset has only 5 months of data (from Jan-May) for 2019... here would we:
- a) throw this data out?
- b) gap-fill? 
- c) use a weighted average?

**Comment by stephpenn1** [comment]
@mlkhorn will work on making a timeseries figure of temperature data with ft events in red, so we can see data availability and potential areas in need of gap-filling

**Comment by bpbond** [comment]
I thought we had already established some minimum criteria, e.g. half of each month represented?

Anyway, for the January-May example, no, I don't think you can reasonably estimate an annual number from that.

If you have decent (at least 2x/month?) coverage, though, sure. Yes, you'd want to extrapolate between dates and then take the mean or sum. So for example, you could use the `approx` function to linearly extrapolate. Happy to go over a more detailed example of this if useful.

**Comment by mlkhorn** [comment]
Coverage When Calculating Annual Rs-
Yes that's correct! Because of code written earlier in the project we can be sure that each dataset included in `winterdata_names` has at least 12 months of data with at least 15 days in each month. However, there are some cases like `d20190617_SCOTT_WKG` that include several years with full coverage (2017, 2018) then a year with partial coverage (just 5 months of data in 2019). I was thinking of treating these extra snippets as extraneous and removing them from my analysis. Does this sound like a good way to address the issue?  

@bpbond

**Comment by bpbond** [comment]
Yes, I'd say any year that doesn't meet the criteria can get dropped?

**Comment by stephpenn1** [comment]
Right, right. So we know each dataset has at least 15 days/month.. and now that your code splits each dataset into each year, we should be able to count no. of months in your `summarise` line.

ex. starting on line 133:

```   
    mutate(year= year(CSR_TIMESTAMP_BEGIN), month = month(CSR_TIMESTAMP_BEGIN)) %>%
    group_by(year) %>%
    summarise(avgRs=mean(CSR_FLUX_CO2), n_months =  count(unique(month))
 ```

I think? @bpbond is this how you'd count no. months in a year?

**Comment by bpbond** [comment]
Yup although consider `dplyr::n_distinct()` for brevity?
