### ISSUE TITLE
Week 7 Goals

### ISSUE THREAD

**Issue by stephpenn1** [mlkhorn/ftc_cosore#14]
- [ ] Create timeseries graph of temperature with freeze-thaw events marked in red
- [x] Identify where we may need to gap-fill or remove data for `Rs_annual` calculation
- [ ] Begin abstract draft [here](https://docs.google.com/document/d/1p9Nh5z1SHUUIM0ffIZoSi7nqWakJQEoXNDTFpTZtAuo/edit): work on the portions that don't include results
- [x] Write code to calculate winter Rs contribution

- [x] SP will email to resolve conflicting abstract deadlines

**Comment by stephpenn1** [comment]
July 9 To do:

### Data Cleaning
- [x] Identify where we don't have a full year of data `length(unique(month))==12`
- [x] Filter them out
- [ ] The definition above completely cuts out two datasets, possibly go back in and reincorporate them using gap filling
- [x] Remove negative CO2 numbers using `filter`

### For winter Rs cont.
- [ ] Filter for winter timestamps only (`filter(Timestamp < "XX:XX:XX", Timestamp > ......`)

### Figure
- [x] Plot T5min
- [ ] Mark ft events (`+ geom_point(data = new_dataset, aes(x = x_vals, y = y_vals`)
- [ ] Possibly format this plot for visual appeal

**Comment by mlkhorn** [comment]
July 10 To Do:

### Other 
- [x] Timesheet
- [x] Journal Club Paper
- [x] Attend Journal Club
- [x] Talk with Julia
- [x] Send email to Ben/Steph about next weeks doctors appts
- [ ] Follow up with Francis about snack group 

### Winter Rs Contribution
- [x] Filter for winter timestamps only
- [x] Calculate winter Rs for each dataset using the calendar definition
- [x] Update code that calculates annual Rs to do so only for the cleaned data
- [x] Calculate the winter contribution to annual Rs for each year in each dataset

### Figure
- [ ] Finish figuring out how to mark ft events in red (`+ geom_point(data = new_dataset, aes(x = x_vals, y = y_vals`)

### Abstract
- [x] Email Julia to ask her to send you the abstract she wrote so you can take a look at it
- [x] Look over Julia's abstract for ideas
- [ ] Prewrite for your abstract to generate ideas
- [ ] Outline abstract in outline google doc
- [ ] Possibly email Stephanie to talk about what you need help with and set up a time to go over the abstract together late on Monday or early on Tuesday
- [x] Remember the abstract is due next Tuesday!
