### ISSUE TITLE
Week 9 Goals

### ISSUE THREAD

**Issue by mlkhorn** [mlkhorn/ftc_cosore#17]
### ANOVA
- [x]  pull in IGBP by joining 
- [x]  define linear model 
- [x] diagnostic plots
- [x] anova

### FT-Events and Winter Rs Contribution Visualization
- [x]  Improve formatting 2
- [x]  Design ANOVA
- [x]  Run ANOVA. 

### FT-Events and Winter Rs Visualization
- [x]  Improve formatting 2
- [x]  Design ANOVA
- [x]  Run ANOVA. 

### Fill in the Blank
- [x]  Fill in the blank in your technical abstract and 
- [x]   submit it to Nicole by July 22

### Temperature Visualization (continuing work from last week)
- [x]  Improve formatting 2

### Presentation
- [x] Remember that your powerpoint slides are due this Wednesday!
- [ ] ....
- [x] Have steph/ben review your work
- [x] Incorporate feedback
- [x] Have steph/ben have review your final product
- [x] Incorporate final comments
- [x] Submit to IR

### Research Paper
- [ ] Remember that your paper is due this Thursday!
- [ ] ...
- [ ] Have steph/ben review your work
- [ ] Incorporate feedback
- [ ] Have steph/ben have review your final product
- [ ] Incorporate final comments
- [ ] Submit to IR

### Friday Stuff
- [ ] Timesheet
- [ ] Email about next weeks dr's appts
- [ ] Meet with algae guy to talk about his research
- [ ] Start issue for next week

**Comment by mlkhorn** [comment]
@bpbond @stephpenn1 draft to do list for next week

**Comment by stephpenn1** [comment]
Looks great!

**Comment by bpbond** [comment]
Agreed :)
