### ISSUE TITLE
R Practice with dplyr, tidyr, and ggplot2

### ISSUE THREAD

**Issue by stephpenn1** [mlkhorn/ftc_cosore#4]
### Helpful Resources
[**dplyr**](https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf)
[**ggplot**](https://github.com/rstudio/cheatsheets/blob/master/data-visualization-2.1.pdf)

### Packages Needed:
`dplyr`
`tidyr`
`ggplot2`
`gapminder` - data package of life expectancy, GDP per capita, and population for 142 countries

## Question 1:
What is the range (hint, hint) of the years in this dataset?

## Question 2:
```
gapminder %>% 
    print(n = 20) %>%  
    summary()
```   
How would you do this in base R (without pipelines)? Think about how functions are structured (_function(argument)_)

## Question 3:
Write a pipeline that prints the average life expectancy for each continent in the last year of the dataset. Note that to do this correctly, you’ll need to weight by country populations. Paste the tibble/dataframe, also note you can use ``` on either side of text to format code in a comment.

```
see! oooo hello I'm code
```

## Question 4:
Write a pipeline that filters for China and returns only the `year` and `lifeExp` columns and **plot** the life expectancy over time. Check out the `select()` function in dplyr.

## Extra Credit Pipeline:
Write a pipeline that computes the year of max population for each country. 

Hint: think about how `dplyr`'s split -> apply -> combine workthrough works.. what would you need to group by? 

## Plotting Challenge:
Using the full `gapminder` dataset, reproduce this plot. Note: the x-axis looks like it's been scaled.

**Hint**: First look at _what_ data is being shown. Has it been filtered? What variables are plotted and how?

![image](https://user-images.githubusercontent.com/20341158/59938041-f498d880-9421-11e9-8544-4257ac07e76e.png)

## Extra-Extra Credit:
Create a plot using  `facet_wrap()`! All other parameters and aesthetics can be of your choosing :-)

**Comment by mlkhorn** [comment]
# rPractice
###### 06/11/2020
###### Mercedes Horn



### Packages

library(gapminder)
library(dplyr)
library(ggplot2)
library(tidyr)



### Question 1

###### checking out the dataset
gapminder 

###### work
range(gapminder[3])

####### answer
#### 1952 to 2007, ie 55 years
 


### Question 2

### checking out what this does
gapminder %>%  
  print(n = 20) %>%  
  summary()

###### work
gapminder[1:20,] 

###### answer
print(gapminder[1:20,])
summary(gapminder)



### Question 3  

###### work
n_distinct(gapminder$continent)

###### answer
gapminder %>%
     filter(year == 2007) %>%
     group_by(continent) %>%
     summarise(lecMean=mean(lifeExp)) %>% 
     print()

```
# A tibble: 5 x 2
continent lecMean
<fct>       <dbl>
  1 Africa       54.8
2 Americas     73.6
3 Asia         70.7
4 Europe       77.6
5 Oceania      80.7

```



### Question 4

###### answer
gapminder %>%
  filter(country == "China") %>% 
  select(year, lifeExp) %>%
  ggplot(aes(x=year,y=lifeExp)) +
  geom_point(color="blue")+
  xlab("Time (years)")+
  ylab("Mean Life Expectancy (years)")+
  ggtitle("Change in Chinese Life Expectancy Over Time")+
  theme_minimal()



### Question 5

###### answer
gapminder %>%    # looking wrong
  group_by(country) %>%
  summarise(maxpop=max(pop), witchy=which())
gapminder %>%    # looking wrong
  group_by(country) %>%
  summarise(maxpopyear=year[which(pop == max(pop))])



### Question 6

###### answer
gapminder %>%
  filter(year == 1967) %>%
  ggplot(aes(x=gdpPercap, y=lifeExp, colour=continent)) +
  geom_point( aes(size=pop)) +
  xlab("GDP per capita") +
  ylab("life expectancy") +
  ggtitle("Year 1967") +
  labs(subtitle="Gapminder Dataset")+
  scale_x_log10()

 

### Question 7 

###### work
library(babynames)

###### answer 1
babynames %>%
filter(name == "Alex") %>% 
ggplot(aes(year, prop)) +
  geom_point()+
  xlab("Time") +
  ylab("Proportion") +
  ggtitle("Use Of The Name Alex Over Time")+
  facet_wrap(~ sex)

###### answer 2
gapminder %>%
  filter(continent == "Europe") %>%
  ggplot(aes(year,pop)) +
  geom_point() +
  facet_wrap( ~ country )

**Comment by mlkhorn** [comment]
@stephpenn1 yay!! here you go!

**Comment by bpbond** [comment]
Nice job @mlkhorn !

Q1: isn't range inclusive, i.e. 56 years?
Q2: I don't think your answer will print the same thing as SP's pipeline code
Q3: yes except see the question–the computation should be weighted by population size. See the `weighted.mean()` function
Q4: looks right although next time please insert figure :)

👏 

Leaving the rest for @stephpenn1

**Comment by bpbond** [comment]
I would also say please commit, or open a PR, with your script!

**Comment by mlkhorn** [comment]
@bpbond @stephpenn1 
Q1: You are definitely right! Looks like its been a little too long since I've taken math. 

Q2: Ah, I see the difference. I will fix that.

Q3: Thanks! I ended up doing that one with Stephanie over teams and we left out that step. I will fix it. 
 
Q4: For sure! Here yah go!
![image](https://user-images.githubusercontent.com/38331537/84663240-e07ba000-aeea-11ea-93e6-2eb1e5dd08b9.png)

**Comment by mlkhorn** [comment]
### Question 2
###### answer
print(gapminder,n=20)
summary(gapminder)

@bpbond does this fix the issue on 2 or am I missing something?

**Comment by bpbond** [comment]
The pipeline code print a summary _of the first 20 rows_. So I think
```R
summary(gapminder[1:20,])
```

**Comment by mlkhorn** [comment]
Hmm I am a little bit confused then because when I run Stephanie's code on my console I get a summary of the entire dataset with the max lifeExp being 82.60 which isn't a lifeExp included in the first 20 rows. 
<img width="447" alt="question2" src="https://user-images.githubusercontent.com/38331537/84666636-55e96f80-aeef-11ea-9874-3456918db773.PNG">
@bpbond

**Comment by bpbond** [comment]
Oh interesting. I could be wrong!

**Comment by mlkhorn** [comment]
Ok, I will leave it how it is for now then.

**Comment by mlkhorn** [comment]
### Question 3  
###### answer
gapminder %>%
     filter(year == 2007) %>%
     group_by(continent) %>%
     summarise(lecMean=weighted.mean(lifeExp,pop)) %>% 
     print()
```
# A tibble: 5 x 2
continent lecMean
<fct>       <dbl>
  1 Africa       54.6
2 Americas     75.4
3 Asia         69.4
4 Europe       77.9
5 Oceania      81.1
```

@bpbond @stephpenn1 does this fix question 3? I guess I am still a little confused about why the question wants me to weight by country population. Was this done for a reason or just to make the question a richer learning experience?

**Comment by bpbond** [comment]
Let's say our continent has two countries, A and B:
* The population of A is 100,000 and they have a life expectancy of 50 years
* The population of B is 100 and they have a life expectancy of 100 years.

What's the average life expectancy of the continent? Is it 75? 🤔

**Comment by mlkhorn** [comment]
No, its definitely not! :) 
It would be something much closer to 50.05. Thanks for the translation @bpbond

**Comment by stephpenn1** [comment]
Nice work @mlkhorn! Few comments:

### Q1:
Good, you can also use  the `$` operator to select a column in a dataframe like so:
```range(gapminder$year)```
This, to me, is a bit more reproducible / easy to follow.

### Q2: 
Yeah, I think I just didn't chose a good function to pipe into this. But you're right, Mercedes, executing my code will `print` the first 20 lines and then summarise the _whole_ dataset... so you are correct.

### Q3: 
Yes @bpbond I agree about the usage of `weighted.mean()`. Your additional comment looks good to me?

### Q4:
Lovely graph!

### Q5:
I think your lines 92-94 are correct, here. You need to use the indices you got from `which` to pull out the rows.

### Q6:
This graph looks lovely to me.. did you have questions about it?

### Q7:
- Cool `babynames` plot! 
- Nice faceted graph :)

## Overall
Great work!!! A few things to change under your `fixes` branch...
- [ ] **Q3**: change to updated code
- [ ] **Q5**: remove the first attempt or comment out
- [ ] I think I made the formatting a little confusing so I apologize: the markdown format with multiple `###`'s are for use in Github issues or RMarkdowns, not necessarily for a `.R` script. I don't think it will affect anything when you run the script. But just as a clarification I meant to write your script and then copy and paste your code answers into the issue comments _using_ markdown formatting. so if I wanted to write formatted code instead of...

gapminder %>%
summary()

I can but three back-ticks (`) before and after for this:

```
gapminder %>%
summary()
```

**Comment by mlkhorn** [comment]
Formatting- ohhhh that helps quite a bit. Will be ready to commit soon @stephpenn1
