### ISSUE TITLE
Week 6 Goals

### ISSUE THREAD

**Issue by stephpenn1** [mlkhorn/ftc_cosore#7]
## Before you work on the analysis, I'd suggest you:
- [x] Clean up and document code, making sure things are easy to find and you understand everything
- [x] Create pull request into `master`, tag me or BBL to review

#### Identify freeze-thaw events:
_Tip: you should create a new branch (from master) for this, titled `ft-events`_
- [x] Identify and pull out COSORE datasets that meet criteria (i.e. `winterdata_names`)
- [x] Calculate daily `T5mean`
- [x] Calculate number of zero crossings / 2 (you’ll want to use the `sign()` function)
**This will give us the number of freeze-thaw events!**

## Misc.
- [ ] Plot the temperature data for each dataset, coloring 0 crossings red
- [ ] If you want to fill in missing data, that’s the `approx()` function in R

## This week's reading:
- @bpbond do you have any?

**Comment by mlkhorn** [comment]
@stephpenn1 I think I just got a little confused by your wording in "create pull request into master" and accidentally committed to master without giving you a chance to review. Is there a way for me to reverse this? It looks like you wanted me to create a branch that diverged from master and then create a pull request that would allow it to be added after review, is that correct? Sorry for the mix up.

**Comment by bpbond** [comment]
This looks good. Generally though @mlkhorn let's plan to have you work on a branch; open a PR to get reviews; and then merge. But all but the most trivial changes, that's a good workflow for a variety of reasons I think. Thanks!

**Comment by mlkhorn** [comment]
sounds like a plan @stephpenn1 @bpbond

**Comment by bpbond** [comment]
Hi @mlkhorn this just published, interesting and relevant: [Snow melt stimulates ecosystem respiration in Arctic ecosystems
](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.15193?af=R)

**Comment by mlkhorn** [comment]
@bpbond Woah cool! I will check it out. Thanks for sharing!
